### ISSUE TITLE
global_admins rename will break fixie

### ISSUE THREAD

**Issue by markan** [chef/fixie#17]
https://github.com/chef/chef-server/pull/251

**Comment by mmzyk** [comment]
@manderson26 Given I've used fixie against the latest server that has that rename, fixie appears to be fine, or else this issue was already addressed.

**Comment by mivok** [comment]
I just ran into an issue surrounding this - running the associations check against a recently created org in hosted showed no global admins group because it was looking for the group with the old name. The group with the new name exists however and works fine.
